Use dict.get() to accelerate convert_index()
nilesr/braille-art pull request #1
Opened 2018-03-30 10:26 UTC by cclauss

Also consolidate image_average()

2018-03-30 12:15 UTC, nilesr commented
Please fix the runtime errors and submit again.
```
 Nutmeg-Yew  Niles  !  ~  braille-art  python3 run.py
Traceback (most recent call last):
  File "run.py", line 26, in <module>
    avg = image_average(x + (char_height_divided * xn), y + (char_width_divided * yn), x + (char_height_divided * (xn + 1)), y + (char_width_divided * (yn + 1)))
  File "run.py", line 17, in image_average
    return average(average(base.getpixel((x, y))[:3]) for x in range(x1, x2) for y in range(y1, y2))
  File "run.py", line 3, in <lambda>
    average = lambda x: sum(x)/len(x) if len(x) > 0 else 0
TypeError: object of type 'generator' has no len()
```

2018-03-30 12:16 UTC, nilesr requested changes
Please fix the runtime errors and resubmit

2018-03-31 06:15 UTC, cclauss commented
Fixed...  Sorry about that.  Please review.

2018-03-31 13:09 UTC, nilesr approved these changes

2018-03-31 13:09 UTC, merged